#!/bin/bash
#####################################################################################
#####################################################################################
##########################    AFAD - guncelleme    #########################################
#####################################################################################
#####################################################################################
#####################################################################################
cd /opt/afad-pardus-yukseltme
cp afad-pardus-yukseltme.desktop /usr/share/applications/
chmod 777 /opt/afad-pardus-yukseltme/afad-pardus-yukseltme.sh
chmod 755 /opt/afad-pardus-yukseltme/19to21.sh
############ Normal kullanıcılara pardus-yukseltme Çalıştırma yetkisi ############################
sudoers_file1=$(less /etc/sudoers |grep 19to21.sh | wc -l)
if [ "$sudoers_file1" -lt "1" ] ; then
echo 'ALL ALL= NOPASSWD: /opt/afad-pardus-yukseltme/19to21.sh' | sudo EDITOR='tee -a' visudo
else 
echo sudoers-ok
fi
